from licensingapp.test_cases.create_license_type import CreateLicenseTypeTests
from licensingapp.test_cases.update_license_type import UpdateLicenseTypeTests
from licensingapp.test_cases.get_license_type import GetLicenseTypeTests
from licensingapp.test_cases.get_all_license_types import GetAllLicenseTypesTests
from licensingapp.test_cases.register_company import RegisterCompanyTests
from licensingapp.test_cases.activate_license import ActivateLicenseTests
from licensingapp.test_cases.increase_total_users import IncreaseTotalUsersTests