# Generated by Django 5.2.4 on 2025-07-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensetype',
            name='duration_type',
            field=models.CharField(choices=[('days', 'DAYS'), ('months', 'MONTHS'), ('years', 'YEARS')], default='months', max_length=10),
        ),
    ]
