# Generated by Django 5.2.4 on 2025-07-17 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensingapp', '0004_companylicense'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylicense',
            name='license_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='licensingapp.licensetype'),
        ),
    ]
